### ISSUE TITLE
Bug: My assignments jupyter notebook are not loading  sometimes or its taking long time to load.

### ISSUE THREAD

**Issue by starboyvarun** [coursera/coursera-labs#26]
I am not able to access jupyter notebooks .ipynb files through Coursera. It takes a long time to load.I am doing several courses in Coursera. Please fix this issue asap. And sometimes it loads but characters symbols or images of .ipynb files do not load properly.
Thanks!

**Comment by ricky-wong** [comment]
Your request is unrelated to this repository:

> This repository provides resources for creating custom images on Coursera Labs.

If you need help, go to https://www.coursera.support/
