### ISSUE TITLE
vscode image doesn't seem to be building on coursera, though builds locally

### ISSUE THREAD

**Issue by nickeubank** [coursera/coursera-labs#37]
I can build it locally, but it keeps choking on this when I upload all the files to Lab Manager:

```
# Set up Chrome Viewer (can't be found on the code-server marketplace currently as of 07/20/2020)
# We don't want to download the vsix file here because it fails too often.
RUN mkdir -p $VSCODE_EXTENSIONS/vscode-browser-preview \
    && bsdtar --strip-components=1 -xf /tmp/auchenberg.vscode-browser-preview-0.6.7.vsix -C $VSCODE_EXTENSIONS/vscode-browser-preview extension
```

I'm getting this error:

```
Removing intermediate container 56c2d883a5ef
---> 56102aa1ebb1
Step 42/95 : RUN mkdir -p $VSCODE_EXTENSIONS/vscode-browser-preview     && bsdtar --strip-components=1 -xf /tmp/auchenberg.vscode-browser-preview-0.6.7.vsix -C $VSCODE_EXTENSIONS/vscode-browser-preview extension
---> Running in 1ee785a1af6a
[91mbsdtar: Error opening archive: Failed to open '/tmp/auchenberg.vscode-browser-preview-0.6.7.vsix'
[0m
The command '/bin/sh -c mkdir -p $VSCODE_EXTENSIONS/vscode-browser-preview     && bsdtar --strip-components=1 -xf /tmp/auchenberg.vscode-browser-preview-0.6.7.vsix -C $VSCODE_EXTENSIONS/vscode-browser-preview extension' returned a non-zero code: 1
End
Failed.  Docker image could not be built.
```

CORRECTION: I'm using a slightly edited version of the [vscode image](https://github.com/nickeubank/coursera-labs/), if that matters, but again: it builds locally fine, I'm just having this issue on upload. 

Any suggestions?

Thanks!

**Comment by echuber2** [comment]
The bsdtar command appears to give that error message if the file is not found. Make sure that the vsix is actually included in the zip you're submitting to Coursera. The file you linked would copy the extensions directory with this line:

https://github.com/nickeubank/coursera-labs/blob/1b03260745666fda2d035be01f499f6467c3fd70/vscode/Dockerfile#L161

If you're sure you've included the file in the directory in the zip, but you had previously built a nearly-identical version that had different extensions in the subfolder, then Coursera's build cache may be causing you trouble. Add a meaningless line near the top of your Dockerfile to invalidate the cache, e.g.:

```dockerfile
RUN echo "Hi, invalidating cache"
```

**Comment by nickeubank** [comment]
Thank you @echuber2 ! Turns out that `zip -R` doesn't zip recursively—you have to use `zip -r`. Sigh. 
🤬
