### ISSUE TITLE
`vscode` folder builds but doesn't launch on coursera

### ISSUE THREAD

**Issue by nickeubank** [coursera/coursera-labs#38]
As part of my never ending quest to successfully get the docker image that I want running to support our data science course, I finally realize I should stop trying to play around with my own modified builds and check to see if the build in this repo will actually run. And... it doesn't. It builds without errors, but when I launch it it hangs at 100% until it times out. 

Below is everything I've done, just to be explicit and to ensure I didn't do something wrong.

Bash commands to zip folder:

```bash
(base) ➜  ~ git clone git@github.com:coursera/coursera-labs.git
Cloning into 'coursera-labs'...
remote: Enumerating objects: 729, done.
remote: Counting objects: 100% (207/207), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 729 (delta 109), reused 170 (delta 80), pack-reused 522
Receiving objects: 100% (729/729), 31.07 MiB | 33.60 MiB/s, done.
Resolving deltas: 100% (282/282), done.
(base) ➜  ~ cd coursera-labs 
(base) ➜  coursera-labs git:(master) cd vscode     
(base) ➜  vscode git:(master) zip -r image_builder.zip * .hidden
  adding: Dockerfile (deflated 66%)
  adding: config.yaml (deflated 39%)
  adding: coursera-launch-button/ (stored 0%)
  adding: coursera-launch-button/__init__.py (stored 0%)
  adding: coursera-launch-button/refreshButtonConfig.py (deflated 66%)
  adding: coursera-submission/ (stored 0%)
  adding: coursera-submission/grading.py (deflated 51%)
  adding: coursera-submission/__init__.py (stored 0%)
  adding: extensions/ (stored 0%)
  adding: extensions/auchenberg.vscode-browser-preview-0.6.7.vsix (deflated 4%)
  adding: extensions/coursera-launch-button-0.0.1.vsix (deflated 10%)
  adding: index.html (stored 0%)
  adding: launchButtonSettings.json (deflated 41%)
  adding: manifest.json (deflated 43%)
  adding: nginx-files/ (stored 0%)
  adding: nginx-files/.hidden (stored 0%)
  adding: nginx-files/refreshProxyConfig.js (deflated 81%)
  adding: nginx-files/package-lock.json (deflated 32%)
  adding: nginx-files/package.json (deflated 35%)
  adding: nginx-files/.readonly (stored 0%)
  adding: nginx-files/reverseProxyConfig.json (deflated 39%)
  adding: nginx-files/reverse-proxy.conf (deflated 77%)
  adding: settings.json (deflated 57%)
  adding: start.sh (deflated 59%)
  adding: supervisord.conf (deflated 58%)
  adding: .hidden (stored 0%)
(base) ➜  vscode git:(master) 
```

I then upload that zipped folder as a custom image in Lab Manager (`Lab Manager` > `Add Image` > `Create a custom image` > upload zip, and clicks `Add image`). 

The image seems to build without problems. The build log is:

[build_log.txt](https://github.com/coursera/coursera-labs/files/9690555/build_log.txt)

Then I click `Test image`. Everything starts out as normal, and it looks like the lab is spinning up, but when it gets to 100% it just hangs:

![image](https://user-images.githubusercontent.com/9683693/193414932-e0776c92-fe6b-44ea-ba0e-c9ad0873ae88.png)

Until eventually I get:

![image](https://user-images.githubusercontent.com/9683693/193414942-ce138a3b-119e-486b-9303-9da8522b23ab.png)

Colleagues ( @kylebradbury ) see the same behavior with my "custom" built images that build successfully.

The one I built above was at this URL, in case useful for anyone internal ( @profmikegreene ): https://www.coursera.org/teach/numpy-data-science/FiD87hWPEey8CQo63UjS5w/content/labs/testzovnxxyn

It's not a *complete* dealbreaker for our course—using a standard base image, adding some docker commands at the end, and then also adding `.vscode` folders with custom `settings.json` files allows us to accomplish most of what we want, but there are couple settings that can't be modified in a workspace `settings.json` files that result in popups every time the image gets launched we worry will confuse/frustrate students.

Any suggestions?

cc: @kylebradbury @mvhudson-duke

**Comment by nickeubank** [comment]
@josephl310 is this a backend thing, since the docker builds but can't load into vs code?

**Comment by josephl310** [comment]
Thanks for the tag Nick! I'm taking a look today.

**Comment by josephl310** [comment]
Could you try setting the HTTP PORT field in the "Edit custom image" from 8888 to 8080? 8888 is the default port for Jupyter images; 8080 is the default port for VSCode.

**Comment by nickeubank** [comment]
OMG. Well, seems like that was the problem! Thanks so much. Gonna add some notes to README as a PR if you don't mind.

**Comment by josephl310** [comment]
You're welcome! I was planning on updating documentation too because this was an issue that I ran into early on too so it's definitely something that should be pointed out.
