### ISSUE TITLE
Suggestions for using `vscode` image autograder?

### ISSUE THREAD

**Issue by nickeubank** [coursera/coursera-labs#40]
OK, now that I have the vscode image (with my edits) up and running for labs (#38 and #39), I'm running into a little trouble with getting the grader setup. @josephl310 sorry to bother you again, but now that my image is a "custom image", the programming assignments no longer seem to know how to get the autograder setup. Previously, with the standard vscode image + some additional docker edits, I had options like this:

![image](https://user-images.githubusercontent.com/9683693/193851464-b3564fd3-66bb-457e-8d55-27927a36b3ed.png)

Easy-Peezy!

But now all I see is this:

![image](https://user-images.githubusercontent.com/9683693/193851235-b0135a19-d03e-4850-a50f-13f2086b6f60.png)

I also tried re-uploading the same image, but that's just spinning. 

Suggestions? There a way to just point to a path in the lab image even if the image is custom?

**Comment by josephl310** [comment]
Hey Nick! You were most likely using one of our VSCode images with a pre-configured grader. Now that you're using a custom image, you'll need to write a separate custom grader for this image. 

Here's the ERC article on custom graders: https://www.coursera.support/s/article/360050380151-Tips-and-Best-Practices-for-Programming-Assignments-and-Custom-Graders?
Here's a repository containing some sample graders: https://github.com/coursera/programming-assignments-demo/tree/master/custom-graders

**Comment by nickeubank** [comment]
Thanks!!
