### ISSUE TITLE
BUG : the search is not working as it supposed to do.

### ISSUE THREAD

**Issue by shivamsharmaameta** [coursera/coursera-labs#46]
on the page https://www.coursera.org/courses?query=free when i click on search on the top and start typing after 4 letter it is printing reverse string eg. it is writting "google" as "googel" and same for other queries.
![Screenshot_2023-09-12_22-08-06](https://github.com/coursera/coursera-labs/assets/105043314/f1dfab31-c178-425a-b036-6f73cc3a3b21)
Supposed : To write correct string provided as input in the search bar.

**Comment by swexler-coursera** [comment]
This repository is for Coursera labs.  For other site issues, please contact Coursera via chat or email. 
 https://www.coursera.support/s/article/360036160591-How-to-contact-Coursera?language=en_US
